
#################################
#version: 
#desc: kibana-x-pack:6.2.4
#version
#
#################################
FROM docker.elastic.co/kibana/kibana-x-pack:6.2.4
MAINTAINER maomao

RUN mkdir temp \
     && apt-get update \
     && apt-get install -y  vim
