
FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
MAINTAINER maomao




COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

## edit origin sh
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
